import { AS, DCTerms, UDFS } from '../namespaces'

export const TaskVocab = {
  title: DCTerms.title,
  instruction: UDFS.instruction,
  prompt: UDFS.prompt,
  issue: UDFS.issue,
  message: UDFS.message,
  thread: UDFS.inThread,
  workspace: UDFS.workspace,
  status: UDFS.status,
  priority: UDFS.priority,
  assignedTo: UDFS.assignedTo,
  source: UDFS.source,
  metadata: UDFS.metadata,
  createdAt: DCTerms.created,
  updatedAt: DCTerms.modified,
} as const

export const DeliveryVocab = {
  kind: UDFS.deliveryKind,
  status: UDFS.status,
  task: UDFS.task,
  source: UDFS.source,
  target: AS.target,
  chat: UDFS.conversation,
  thread: UDFS.inThread,
  targetThread: UDFS.targetThread,
  targetSession: UDFS.targetSession,
  actor: AS.actor,
  object: AS.object,
  objective: UDFS.objective,
  payload: UDFS.payload,
  projection: UDFS.projection,
  projectedRole: UDFS.projectedRole,
  metadata: UDFS.metadata,
  error: UDFS.error,
  createdAt: DCTerms.created,
  dispatchedAt: UDFS.startedAt,
  consumedAt: UDFS.consumedAt,
  completedAt: UDFS.completedAt,
  updatedAt: DCTerms.modified,
} as const

export const RunVocab = {
  task: UDFS.task,
  delivery: UDFS.delivery,
  trigger: UDFS.trigger,
  input: UDFS.input,
  thread: UDFS.inThread,
  workspace: UDFS.workspace,
  status: UDFS.status,
  runner: UDFS.runner,
  prompt: UDFS.prompt,
  externalRunId: UDFS.externalRunId,
  leaseOwner: UDFS.leaseOwner,
  leaseExpiresAt: UDFS.leaseExpiresAt,
  heartbeatAt: UDFS.heartbeatAt,
  cancelRequestedAt: UDFS.cancelRequestedAt,
  error: UDFS.error,
  metadata: UDFS.metadata,
  createdAt: DCTerms.created,
  startedAt: UDFS.startedAt,
  completedAt: UDFS.completedAt,
  updatedAt: DCTerms.modified,
} as const

export const RunStepVocab = {
  run: UDFS.run,
  stepType: UDFS.stepType,
  message: DCTerms.description,
  data: UDFS.metadata,
  createdAt: DCTerms.created,
} as const
