import { podTable, uri, string, timestamp, id } from '@undefineds.co/drizzle-solid'
import { RDF, ODRL, UDFS, DCTerms } from './namespaces.js'

// Persistent delegation grants generated by "do not ask again" decisions.
// This is the durable "delegation" layer (distinct from one-off approvals and append-only audit entries).
export const grantTable = podTable(
  'grant',
  {
    id: id('id'),

    // Also tag the instance with our company-level class for easy discovery.
    // Primary rdf:type is ODRL.Policy (standard).
    rdfType: uri('rdfType').predicate(RDF.type).notNull().default(UDFS.AutonomyGrant),

    // Minimal ODRL surface (CP0): allow/deny action on target.
    target: uri('target').predicate(ODRL.target).notNull(),
    action: uri('action').predicate(ODRL.action).notNull(),

    // Extensions
    effect: string('effect').predicate(UDFS.effect).notNull(),
    riskCeiling: string('riskCeiling').predicate(UDFS.riskCeiling),

    // Delegation identity (WebID semantics)
    decisionBy: uri('decisionBy').predicate(UDFS.decisionBy).notNull(),
    decisionRole: string('decisionRole').predicate(UDFS.decisionRole).notNull(),
    onBehalfOf: uri('onBehalfOf').predicate(UDFS.onBehalfOf),

    // Lifecycle
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    revokedAt: timestamp('revokedAt').predicate(UDFS.revokedAt),
  },
  {
    base: '/settings/autonomy/grants/',
    sparqlEndpoint: '/settings/autonomy/grants/-/sparql',
    type: ODRL.Policy,
    namespace: ODRL,
    subjectTemplate: '{id}.ttl',
  },
)

export type GrantRow = typeof grantTable.$inferSelect
export type GrantInsert = typeof grantTable.$inferInsert
export type GrantUpdate = typeof grantTable.$inferUpdate
