import { podTable, uri, string, text, timestamp, id } from '@undefineds.co/drizzle-solid'
import { RDF, ODRL, UDFS, DCTerms } from './namespaces'

export function buildGrantSubjectPath(grantId: string): string {
  return `/settings/autonomy/grants/${encodeURIComponent(grantId)}.ttl`
}

// Persistent delegation grant resource generated by "do not ask again" decisions.
// This is the durable "delegation" layer (distinct from one-off approvals and append-only audit entries).
export const grantResource = podTable(
  'grant',
  {
    id: id('id'),

    // Resource-level type writes odrl:Policy. Keep the project-specific class as
    // an additional rdf:type, so readback treats RDF class membership as multi-valued.
    rdfType: uri('rdfType').array().predicate(RDF.type).notNull().default([UDFS.AutonomyGrant]),

    // Minimal ODRL surface (CP0): allow/deny action on target.
    target: uri('target').predicate(ODRL.target).notNull(),
    action: uri('action').predicate(ODRL.action).notNull(),

    // Pod version of the LLM Wiki page contract. The grant remains an ODRL
    // policy, but its maintainable surface is a wiki page with provenance.
    title: string('title').predicate(DCTerms.title),
    summary: text('summary').predicate(UDFS.summary),
    body: text('body').predicate(UDFS.body),
    schema: uri('schema').predicate(DCTerms.conformsTo),
    pageKind: string('pageKind').predicate(UDFS.pageKind),
    wikiStatus: string('wikiStatus').predicate(UDFS.status),
    tags: text('tags').predicate(UDFS.tags),
    source: string('source').predicate(UDFS.source),
    sourceHash: string('sourceHash').predicate(UDFS.sourceHash),
    compiledAt: timestamp('compiledAt').predicate(UDFS.compiledAt),
    compiledFrom: uri('compiledFrom').array().predicate(UDFS.compiledFrom),
    related: uri('related').array().predicate(UDFS.related),

    // Extensions
    effect: string('effect').predicate(UDFS.effect).notNull(),
    riskCeiling: string('riskCeiling').predicate(UDFS.riskCeiling),
    policy: text('policy').predicate(UDFS.policy),
    context: text('context').predicate(UDFS.context),

    // Delegation identity (WebID semantics)
    decisionBy: uri('decisionBy').predicate(UDFS.decisionBy).notNull(),
    decisionRole: string('decisionRole').predicate(UDFS.decisionRole).notNull(),
    onBehalfOf: uri('onBehalfOf').predicate(UDFS.onBehalfOf),

    // Lifecycle
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    revokedAt: timestamp('revokedAt').predicate(UDFS.revokedAt),
  },
  {
    base: '/settings/autonomy/grants/',
    sparqlEndpoint: '/settings/autonomy/grants/-/sparql',
    type: ODRL.Policy,
    namespace: ODRL,
    subjectTemplate: '{id}.ttl',
  },
)

// Compatibility alias. New model code should prefer `grantResource`.
export const grantTable = grantResource

export type GrantRow = typeof grantResource.$inferSelect
export type GrantInsert = typeof grantResource.$inferInsert
export type GrantUpdate = typeof grantResource.$inferUpdate
