import { boolean, id, integer, object, podTable, string, text, timestamp, uri } from '@undefineds.co/drizzle-solid'
import { DCTerms, SCHEMA, SIOC, UDFS, WF } from './namespaces'
import { chatResource } from './chat.schema'
import { messageResource } from './message.schema'
import {
  matrixAccountResourceId,
  matrixEventResourceId,
  matrixRoomResourceId,
} from './resource-id-defaults'

export type MatrixRoomVisibilityType = 'private' | 'public'
export type MatrixMembershipType = 'join' | 'invite' | 'leave' | 'ban'

export const MatrixRoomVisibility = {
  PRIVATE: 'private',
  PUBLIC: 'public',
} as const

export const MatrixMembership = {
  JOIN: 'join',
  INVITE: 'invite',
  LEAVE: 'leave',
  BAN: 'ban',
} as const

/**
 * Matrix account/device state owned by a Pod.
 *
 * This resource records the Matrix protocol identity projected from a Solid
 * identity. Tokens are represented by hashes only; API handlers own raw token
 * issuance/verification.
 */
export const matrixAccountResource = podTable(
  'matrix_account',
  {
    id: id('id').default(matrixAccountResourceId),
    matrixUserId: string('matrixUserId').predicate(UDFS.matrixUserId).notNull(),
    webId: uri('webId').predicate(UDFS.term('webId')).notNull(),
    displayName: string('displayName').predicate(SCHEMA.name),
    avatarUrl: uri('avatarUrl').predicate(SCHEMA.image),
    deviceId: string('deviceId').predicate(UDFS.matrixDeviceId),
    accessTokenHash: string('accessTokenHash').predicate(UDFS.matrixAccessTokenHash),
    metadata: object('metadata').predicate(UDFS.metadata),
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    updatedAt: timestamp('updatedAt').predicate(DCTerms.modified).notNull().defaultNow(),
  },
  {
    base: '/.data/matrix/',
    sparqlEndpoint: '/.data/matrix/-/sparql',
    type: UDFS.MatrixAccount,
    namespace: UDFS,
  },
)

/**
 * Matrix room projected into Pod storage.
 *
 * `chat` links the protocol room to the existing Solid Chat conversation
 * resource so Matrix messages can also participate in xpod chat views.
 */
export const matrixRoomResource = podTable(
  'matrix_room',
  {
    id: id('id').default(matrixRoomResourceId),
    matrixRoomId: string('matrixRoomId').predicate(UDFS.matrixRoomId).notNull(),
    canonicalAlias: string('canonicalAlias').predicate(UDFS.matrixRoomAlias),
    name: string('name').predicate(DCTerms.title),
    topic: text('topic').predicate(DCTerms.description),
    creator: uri('creator').predicate(UDFS.term('creator')),
    visibility: string('visibility').predicate(UDFS.status).notNull().default(MatrixRoomVisibility.PRIVATE),
    roomVersion: string('roomVersion').predicate(UDFS.matrixRoomVersion).default('11'),
    federate: boolean('federate').predicate(UDFS.term('federate')).default(false),
    chat: uri('chat').predicate(UDFS.conversation).link(chatResource),
    members: uri('members').array().predicate(WF.participant),
    metadata: object('metadata').predicate(UDFS.metadata),
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    updatedAt: timestamp('updatedAt').predicate(DCTerms.modified).notNull().defaultNow(),
  },
  {
    base: '/.data/matrix/',
    sparqlEndpoint: '/.data/matrix/-/sparql',
    type: UDFS.MatrixRoom,
    namespace: UDFS,
  },
)

/**
 * Matrix event resource.
 *
 * Events are date-bucketed under their room and can optionally link to the
 * xpod/Solid Chat message generated by the same protocol send operation.
 */
export const matrixEventResource = podTable(
  'matrix_event',
  {
    id: id('id').default(matrixEventResourceId),
    matrixEventId: string('matrixEventId').predicate(UDFS.matrixEventId).notNull(),
    matrixRoomId: string('matrixRoomId').predicate(UDFS.matrixRoomId).notNull(),
    room: uri('room').predicate(SIOC.hasContainer).link(matrixRoomResource),
    type: string('type').predicate(UDFS.matrixEventType).notNull(),
    stateKey: string('stateKey').predicate(UDFS.matrixStateKey),
    sender: string('sender').predicate(UDFS.matrixSender).notNull(),
    senderWebId: uri('senderWebId').predicate(UDFS.matrixSenderWebId),
    originServerTs: integer('originServerTs').predicate(UDFS.matrixOriginServerTs).notNull(),
    depth: integer('depth').predicate(UDFS.matrixDepth).notNull().default(1),
    txnId: string('txnId').predicate(UDFS.matrixTxnId),
    content: object('content').predicate(UDFS.messageContent).notNull(),
    unsigned: object('unsigned').predicate(UDFS.matrixUnsigned),
    redacts: uri('redacts').predicate(UDFS.term('redacts')),
    relatedMessage: uri('relatedMessage').predicate(WF.message).link(messageResource),
    metadata: object('metadata').predicate(UDFS.metadata),
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    updatedAt: timestamp('updatedAt').predicate(DCTerms.modified),
  },
  {
    base: '/.data/matrix/',
    sparqlEndpoint: '/.data/matrix/-/sparql',
    type: UDFS.MatrixEvent,
    namespace: UDFS,
  },
)

export const matrixAccountTable = matrixAccountResource
export const matrixRoomTable = matrixRoomResource
export const matrixEventTable = matrixEventResource

export type MatrixAccountRow = typeof matrixAccountResource.$inferSelect
export type MatrixAccountInsert = typeof matrixAccountResource.$inferInsert
export type MatrixAccountUpdate = typeof matrixAccountResource.$inferUpdate
export type MatrixRoomRow = typeof matrixRoomResource.$inferSelect
export type MatrixRoomInsert = typeof matrixRoomResource.$inferInsert
export type MatrixRoomUpdate = typeof matrixRoomResource.$inferUpdate
export type MatrixEventRow = typeof matrixEventResource.$inferSelect
export type MatrixEventInsert = typeof matrixEventResource.$inferInsert
export type MatrixEventUpdate = typeof matrixEventResource.$inferUpdate
