import { FOAF, VCARD, LDP, DCTERMS, RDF as RDF_VOCAB, ACL as ACL_VOCAB } from '@inrupt/vocab-common-rdf'

type NamespaceObject = ((term: string) => string) & {
  prefix: string
  uri: string
  NAMESPACE: string
  term: (name: string) => string
} & Record<string, string>

const ABSOLUTE_IRI = /^[a-zA-Z][a-zA-Z\d+.-]*:/

const createNamespace = (prefix: string, baseUri: string, terms: Record<string, string>): NamespaceObject => {
  const builder = ((term: string) =>
    ABSOLUTE_IRI.test(term) ? term : `${baseUri}${term}`) as NamespaceObject
  builder.prefix = prefix
  builder.uri = baseUri
  builder.NAMESPACE = baseUri
  builder.term = (name: string) => builder(name)
  Object.entries(terms).forEach(([key, local]) => {
    Object.defineProperty(builder, key, {
      value: builder(local),
      enumerable: true,
    })
  })
  return builder
}

export { FOAF, VCARD, LDP }
export const DCTerms = DCTERMS
export const RDF = RDF_VOCAB
export const ACL = ACL_VOCAB

// ODRL isn't provided as a NamespaceConfig-compatible builder in vocab-common-rdf.
// We define a small namespace builder to keep drizzle-solid happy.
export const ODRL = createNamespace('odrl', 'http://www.w3.org/ns/odrl/2/', {
  Policy: 'Policy',
  target: 'target',
  action: 'action',
})

export const RDFS = createNamespace('rdfs', 'http://www.w3.org/2000/01/rdf-schema#', {
  Class: 'Class',
  label: 'label',
  comment: 'comment',
  subClassOf: 'subClassOf',
  domain: 'domain',
  range: 'range',
})

export const OWL = createNamespace('owl', 'http://www.w3.org/2002/07/owl#', {
  Ontology: 'Ontology',
  Class: 'Class',
  ObjectProperty: 'ObjectProperty',
  DatatypeProperty: 'DatatypeProperty',
})

export const SCHEMA = createNamespace('schema', 'http://schema.org/', {
  CreativeWork: 'CreativeWork',
  MediaObject: 'MediaObject',
  PropertyValue: 'PropertyValue',
  about: 'about',
  author: 'author',
  dateCreated: 'dateCreated',
  dateDeleted: 'dateDeleted',
  description: 'description',
  encodingFormat: 'encodingFormat',
  fileSize: 'fileSize',
  image: 'image',
  name: 'name',
  participant: 'participant',
  reviewedBy: 'reviewedBy',
  text: 'text',
  url: 'url',
})

export const SIOC = createNamespace('sioc', 'http://rdfs.org/sioc/ns#', {
  Container: 'Container',
  Post: 'Post',
  Thread: 'Thread',
  Forum: 'Forum',
  content: 'content',
  richContent: 'richContent',
  hasReply: 'has_reply',
  replyOf: 'reply_of',
  hasCreator: 'has_creator',
  createdAt: 'created_at',
  hasContainer: 'has_container',
  has_parent: 'has_parent',
  numReplies: 'num_replies',
  has_member: 'has_member',
})

export const MEETING = createNamespace('mee', 'http://www.w3.org/ns/pim/meeting#', {
  LongChat: 'LongChat',
  Message: 'Message',
})

export const WF = createNamespace('wf', 'http://www.w3.org/2005/01/wf/flow-1.0#', {
  message: 'message',
  participation: 'participation',
  participant: 'participant',
})

// Activity Streams 2.0 - W3C standard for social web
export const AS = createNamespace('as', 'https://www.w3.org/ns/activitystreams#', {
  Activity: 'Activity',
  Announce: 'Announce',
  Public: 'Public',
  audience: 'audience',
  actor: 'actor',
  object: 'object',
  target: 'target',
})

// Company-level namespace (community-first guidance): all custom terms live under udfs:.
// NOTE: This base URI is part of the contract.
export const UDFS = createNamespace('udfs', 'https://undefineds.co/ns#', {
  // Types
  ApprovalRequest: 'ApprovalRequest',
  InputRequest: 'InputRequest',
  CaptureCandidate: 'CaptureCandidate',
  CaptureEvent: 'CaptureEvent',
  AuditEntry: 'AuditEntry',
  AutonomyGrant: 'AutonomyGrant',
  Idea: 'Idea',
  Issue: 'Issue',
  Task: 'Task',
  Schedule: 'Schedule',
  AutomationRule: 'AutomationRule',
  Delivery: 'Delivery',
  Run: 'Run',
  RunStep: 'RunStep',
  Evidence: 'Evidence',
  Report: 'Report',
  Credential: 'Credential',
  ApiKeyCredential: 'ApiKeyCredential',
  OAuthCredential: 'OAuthCredential',
  Provider: 'Provider',
  Model: 'Model',
  AIConfig: 'AIConfig',
  VectorStore: 'VectorStore',
  IndexedFile: 'IndexedFile',
  AgentStatus: 'AgentStatus',
  GatewayAccessKey: 'GatewayAccessKey',
  QuotaSnapshot: 'QuotaSnapshot',
  Skill: 'Skill',
  name: 'name',
  favorite: 'favorite',
  favoriteType: 'favoriteType',
  favoriteTarget: 'favoriteTarget',
  favoredAt: 'favoredAt',
  conversation: 'conversation',
  conversationType: 'conversationType',
  conversationTitle: 'conversationTitle',
  lastMessage: 'lastMessage',
  lastActiveAt: 'lastActiveAt',
  lastSyncedAt: 'lastSyncedAt',
  sortKey: 'sortKey',
  hasThread: 'hasThread',
  inThread: 'inThread',
  inScope: 'inScope',
  participants: 'participants',
  message: 'message',
  messageContent: 'messageContent',
  messageType: 'messageType',
  messageStatus: 'messageStatus',
  readBy: 'readBy',
  Contact: 'Contact',
  PersonContact: 'PersonContact',
  AgentContact: 'AgentContact',
  GroupContact: 'GroupContact',
  hasContact: 'hasContact',
  contactType: 'contactType',
  externalPlatform: 'externalPlatform',
  externalId: 'externalId',
  alias: 'alias',
  aiAssistant: 'aiAssistant',
  aiModel: 'aiModel',
  aiModels: 'aiModels',
  aiProvider: 'aiProvider',
  credential: 'credential',
  systemPrompt: 'systemPrompt',
  temperature: 'temperature',
  maxTokens: 'maxTokens',
  systemMessage: 'systemMessage',
  provider: 'provider',
  model: 'model',
  displayName: 'displayName',
  proxyUrl: 'proxyUrl',
  hasModel: 'hasModel',
  defaultModel: 'defaultModel',
  modelType: 'modelType',
  isProvidedBy: 'isProvidedBy',
  dimension: 'dimension',
  supportsBackend: 'supportsBackend',
  rotationPolicy: 'rotationPolicy',
  metadata: 'metadata',
  root: 'root',
  webId: 'webId',
  hasSkill: 'hasSkill',
  skill: 'skill',
  enabled: 'enabled',
  version: 'version',
  checksum: 'checksum',
  loadPolicy: 'loadPolicy',
  credentialSource: 'credentialSource',
  backend: 'backend',
  runtime: 'runtime',
  transport: 'transport',
  endpoint: 'endpoint',
  authorityPolicy: 'authorityPolicy',
  toolPolicy: 'toolPolicy',
  runtimeSnapshot: 'runtimeSnapshot',
  tools: 'tools',
  contextWindow: 'contextWindow',
  contextRound: 'contextRound',
  Agent: 'Agent',
  agentCapability: 'agentCapability',
  agentTool: 'agentTool',
  agentConfig: 'agentConfig',
  fileHash: 'fileHash',
  syncStatus: 'syncStatus',
  localPath: 'localPath',
  isDefault: 'isDefault',
  service: 'service',
  label: 'label',
  owner: 'owner',
  secretHash: 'secretHash',
  deployment: 'deployment',
  balance: 'balance',
  windows: 'windows',
  observedAt: 'observedAt',
  lastUsedAt: 'lastUsedAt',
  failCount: 'failCount',
  rateLimitResetAt: 'rateLimitResetAt',
  authMode: 'authMode',
  storageMode: 'storageMode',
  secretPayload: 'secretPayload',
  encryptedSecret: 'encryptedSecret',
  wrappedDataKey: 'wrappedDataKey',
  encryptionAlgorithm: 'encryptionAlgorithm',
  keyVersion: 'keyVersion',
  scopes: 'scopes',
  accountLabel: 'accountLabel',
  lastRefreshAt: 'lastRefreshAt',
  reauthRequired: 'reauthRequired',
  oauthRefreshToken: 'oauthRefreshToken',
  oauthAccessToken: 'oauthAccessToken',
  oauthExpiresAt: 'oauthExpiresAt',
  projectId: 'projectId',
  organizationId: 'organizationId',
  secretType: 'secretType',
  settingKey: 'settingKey',
  settingValue: 'settingValue',
  settingType: 'settingType',
  apiKey: 'apiKey',
  baseUrl: 'baseUrl',
  inbox: 'inbox',
  issue: 'issue',
  task: 'task',
  schedule: 'schedule',
  automationRule: 'automationRule',
  delivery: 'delivery',
  deliveryKind: 'deliveryKind',
  scheduleKind: 'scheduleKind',
  ruleKind: 'ruleKind',
  instruction: 'instruction',
  input: 'input',
  inputRequest: 'inputRequest',
  captureCandidate: 'captureCandidate',
  captureEvent: 'captureEvent',
  captureDecision: 'captureDecision',
  targetResource: 'targetResource',
  suggestedType: 'suggestedType',
  suggestedTarget: 'suggestedTarget',
  confidence: 'confidence',
  userCorrection: 'userCorrection',
  trigger: 'trigger',
  condition: 'condition',
  actions: 'actions',
  objective: 'objective',
  payload: 'payload',
  projection: 'projection',
  target: 'target',
  targetThread: 'targetThread',
  targetSession: 'targetSession',
  projectedRole: 'projectedRole',
  consumedAt: 'consumedAt',
  priority: 'priority',
  commitment: 'commitment',
  affectedArea: 'affectedArea',
  currentUnderstanding: 'currentUnderstanding',
  openQuestions: 'openQuestions',
  conflicts: 'conflicts',
  nextStep: 'nextStep',
  promotedTo: 'promotedTo',
  sourceMessage: 'sourceMessage',
  parentIssue: 'parentIssue',
  session: 'session',
  status: 'status',
  risk: 'risk',
  assignedTo: 'assignedTo',
  reason: 'reason',
  resolvedAt: 'resolvedAt',
  closedAt: 'closedAt',
  action: 'action',
  actor: 'actor',
  actorRole: 'actorRole',
  entry: 'entry',
  context: 'context',
  policy: 'policy',
  pageKind: 'pageKind',
  summary: 'summary',
  body: 'body',
  tags: 'tags',
  source: 'source',
  sourceKind: 'sourceKind',
  sourceHash: 'sourceHash',
  compiledAt: 'compiledAt',
  compiledFrom: 'compiledFrom',
  related: 'related',
  approval: 'approval',
  approvalOptions: 'approvalOptions',
  inputOptions: 'inputOptions',
  requestKind: 'requestKind',
  requester: 'requester',
  response: 'response',
  answeredBy: 'answeredBy',
  effect: 'effect',
  expiresAt: 'expiresAt',
  riskCeiling: 'riskCeiling',
  revokedAt: 'revokedAt',
  archivedAt: 'archivedAt',
  deletedAt: 'deletedAt',
  pinnedAt: 'pinnedAt',
  pinned: 'pinned',
  muted: 'muted',
  mutedAt: 'mutedAt',
  unreadCount: 'unreadCount',
  ttsModel: 'ttsModel',
  videoModel: 'videoModel',
  chatType: 'chatType',
  workspace: 'workspace',
  container: 'container',
  policyRef: 'policyRef',
  policyVersion: 'policyVersion',
  parentThread: 'parentThread',
  sessionStatus: 'sessionStatus',
  runner: 'runner',
  prompt: 'prompt',
  externalRunId: 'externalRunId',
  leaseOwner: 'leaseOwner',
  leaseExpiresAt: 'leaseExpiresAt',
  heartbeatAt: 'heartbeatAt',
  cancelRequestedAt: 'cancelRequestedAt',
  startedAt: 'startedAt',
  startsAt: 'startsAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt',
  nextRunAt: 'nextRunAt',
  lastRunAt: 'lastRunAt',
  lastTriggeredAt: 'lastTriggeredAt',
  lastRunStatus: 'lastRunStatus',
  cron: 'cron',
  intervalSeconds: 'intervalSeconds',
  timezone: 'timezone',
  error: 'error',
  run: 'run',
  stepType: 'stepType',
  evidence: 'evidence',
  evidenceKind: 'evidenceKind',
  report: 'report',
  reportKind: 'reportKind',
  outcome: 'outcome',
  metricFacts: 'metricFacts',
  publishedAt: 'publishedAt',
  reviewer: 'reviewer',
  sessionTool: 'sessionTool',
  tokenUsage: 'tokenUsage',
  embeddingModel: 'embeddingModel',
  previousModel: 'previousModel',
  migrationStatus: 'migrationStatus',
  migrationProgress: 'migrationProgress',
  chunkingStrategy: 'chunkingStrategy',
  fileUrl: 'fileUrl',
  vectorId: 'vectorId',
  usageBytes: 'usageBytes',
  lastError: 'lastError',
  indexedAt: 'indexedAt',
  lastActivityAt: 'lastActivityAt',
  errorMessage: 'errorMessage',
  groupOwner: 'groupOwner',
  groupAdmin: 'groupAdmin',
  senderName: 'senderName',
  senderAvatarUrl: 'senderAvatarUrl',
  mentions: 'mentions',
  replyTo: 'replyTo',
  routedBy: 'routedBy',
  routeTargetAgent: 'routeTargetAgent',
  coordinationId: 'coordinationId',
  agent: 'agent',
  toolCallId: 'toolCallId',
  toolName: 'toolName',
  toolArguments: 'toolArguments',
  toolStatus: 'toolStatus',
  toolResult: 'toolResult',
  toolError: 'toolError',
  toolDuration: 'toolDuration',
  toolRisk: 'toolRisk',
  approvalStatus: 'approvalStatus',
  decisionBy: 'decisionBy',
  decisionRole: 'decisionRole',
  onBehalfOf: 'onBehalfOf',
  approvalReason: 'approvalReason',
  inboxItemId: 'inboxItemId',
  taskProgressId: 'taskProgressId',
  taskSteps: 'taskSteps',
  currentStep: 'currentStep',
  totalSteps: 'totalSteps',

  // Favorites V2
  sourceModule: 'sourceModule',
  searchText: 'searchText',
  snapshotMeta: 'snapshotMeta',
})

export const UDFS_NAMESPACE = UDFS.NAMESPACE
