export {
  workspaceTable,
  WORKSPACE_TYPES,
  WORKSPACE_KINDS,
  getWorkspaceContainerPath,
  resolveWorkspaceContainerUri,
  parseWorkspaceIdFromContainerUri,
  normalizeLocalWorkspacePath,
  buildLocalWorkspaceUri,
  parseLocalWorkspaceUri,
  isLocalWorkspaceUri,
  type WorkspaceType,
  type WorkspaceKind,
  type WorkspaceRow,
  type WorkspaceInsert,
  type WorkspaceUpdate,
} from './core.js'
